# Site settings
title: Diwakar Moturu
SEOTitle: Diwakar Moturu
header-img: https://unsplash.it/1900/870/?random
email: diwakar03121997@gmail.com
description: "Not so bad programmer trying to debug everything from Life to Code"
keyword: ""
url: "https://magician03.github.io/"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: true
github_username:    magician03
twitter_username:  magician_03
facebook_username:  magician03
stackoverflow_username: 4820340/diwakar-moturu
quora_username: Diwakar-Vinay
googleplus_username: +diwakarkumar03121997
linkedin_username: in/diwakar-moturu-63219610a



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 7
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: magician03

# Duoshuo settings
#duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-98852508-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Indian | 19 | Programmer | GSoC'17 | IIITA | Algorithms | Software Engineering | Open Sources | @magician03 | Chef | Gardener"
sidebar-avatar: /img/profile.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
#friends: [
#    {
#        title: "Hux Blog",
#        href: "http://huangxuan.me"
#    },{
#        title: "Foo",
#        href: "#"
#    },{
#        title: "Bar",
#        href: "#"
#    },{
#        title: "Example Friends",
#        href: "#"
#    },{
#        title: "It helps SEO",
#        href: "#"
#    }
#]
